<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Nestly.Seeder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Nestly.Domain/Nestly.Domain.csproj" />
    <ProjectReference Include="../Nestly.Search/Nestly.Search.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
